### ISSUE TITLE
добавить totalTokensNum

### ISSUE THREAD

**Issue by pnazarov** [Terentyev/SmallWorld#33]
gameState->players[i]->totalTokensNum
общее количество фигурок расы на карте (в руках + по регионам)

**Comment by Terentyev** [comment]
Тесты писать не стал.

**Comment by pnazarov** [comment]
totalTokensNum должно быть для каждой расы отдельно и находиться в currentTokenBadge и declinedTokenBadge

я затупил в описании :(
