### ISSUE TITLE
Рафаэль: вызов метода у удаленного объекта

### ISSUE THREAD

**Issue by Terentyev** [Terentyev/SmallWorld#73]
https://github.com/DmitryBaranovskiy/raphael/issues/455
Вот здесь вроде лежат исходники рафаэля, а эта ссылка -- на иш с похожей на нашу ошибкой.

**Comment by Terentyev** [comment]
Я понял в какой момент происходит эта ошибка. Когда у меня уже есть раса в упадке и на карте еще остались от нее фигурки. В этот момент я отказываюсь от активной расы и нажимаю finish turn. И рафаэль падает с ошибкой

**Comment by pnazarov** [comment]
проблема была в следующем регион считал что у него tokensNum = 0 с сервера приходило поле tokensNum не приходило т.е. tokensNum = undef и регион считал что надо обновиться
пофиксил. иш пока не закрываю мало ли что)

**Comment by Terentyev** [comment]
Иши можно открывать, если вдруг надо =)))
