### ISSUE TITLE
Завести на клиенте состояние игры GS_WATCH

### ISSUE THREAD

**Issue by Terentyev** [Terentyev/SmallWorld#91]
Это состояние будет высчитываться в функции prepare (game.js) <=> текущий пользователь отсутствует в массиве активных игроков игры.

Например, можно усовершенствовать конструктор игрока так, что бы он создавал игрока только для игроков inGame == true. Тогда в функции prepare сделать самой первой проверку, что player.p == null => GS_WATCH

Должно помочь исправить ряд ошибок (наверное, даже можно будет таким образом просматривать результат игры, даже когда она пустая)

**Comment by pnazarov** [comment]
не потребовалось
